#!/bin/sh
touch /tmp/u-boot-monitor-socket
qemu-system-riscv32 -machine virt -m 1G \
-kernel u-boot -nographic \
-device virtio-net-device,netdev=user \
-netdev user,id=user,tftp=../tftp \
-monitor unix:/tmp/u-boot-monitor-socket,server,nowait
