#!/bin/sh
touch /tmp/u-boot-monitor-socket
qemu-system-riscv64 -machine virt -m 1G \
-kernel u-boot -nographic \
-device virtio-net-device,netdev=net0 \
-netdev user,id=net0,tftp=../tftp \
-monitor unix:/tmp/u-boot-monitor-socket,server,nowait
